# coding=utf-8
from django.utils.translation import ugettext as _

_TOPIC_CHOICES = (('', _(u'Selecciona una categoria')),
                  ('gobierno_digital_y_modernizacion_de_la_gestion_publica', _(u'Gobierno Digital y modernizacion de la gestion publica')),
                  ('educacion_salud_seguridad_alimentaria_y_nutricional', _(u'Educacion, salud, seguridad alimentaria y nutricional')),
                  ('gestion_publica_e_inclusion_social', _(u'Gestion publica e inclusion social')),
                  ('medio_ambiente_cambio_climatico_y_gestion_integral_para_la_reduccion_del_riesgo_a_desastres', _(
                      u'Medio ambiente, cambio climatico y gestion integral para la reduccion del riesgo a desastres')),
                  ('reduccion_de_la_pobreza_y_migracion', _(u'Reduccion de la pobreza y migracion')),
                  )

_TOPIC_DESCRIPTIONS = (
    ('gobierno_digital_y_modernizacion_de_la_gestion_publica', _(u'Acercar el gobierno a la ciudadania a traves del uso de tecnologia de informacion y comunicacion es fundamental para la consolidacion del proceso de modernizacion de la gestion publica y reforma del Estado, siendo base fundamental para fortalecer los entes administrativos y acercar la prestacion de servicios publicos a la ciudadania como una de las bases para la consolidacion de gobiernos abiertos, a traves de la consolidacion del proceso de desconcentracion de la prestacion de servicios publicos. Asimismo, a traves del fomento del uso de tecnologias de informacion y comunicacion por medio de nuevas herramientas y estrategias publicas, se contribuye al proceso de incrementar la transparencia en el ejercicio de la gestion publica por medio de herramientas tecnologicas que contribuyan al establecimiento de acciones en materia de auditoria social, fiscalizacion y rendicion de cuentas sobre la administracion de la gestion de los gobiernos y del uso y transparencia de la ejecucion de los fondos publicos. La inclusion del gobierno digital en el Plan de Accion Nacional de Gobierno Abierto contribuira a fortalecer los principios de Transparencia y participacion ciudadana propugnados por la Alianza Mundial para el Gobierno Abierto.')),
    ('educacion_salud_seguridad_alimentaria_y_nutricional', _(u'La garantia de los derechos economicos y sociales como el derecho a la salud, es de caracter fundamental, especialmente tomando en cuenta la coyuntura nacional e internacional COVID-19. El ejercicio de procesos de auditoria social que tomen como base el seguimiento a los recursos ejecutados durante la coyuntura COVID 19, genera a nivel nacional un ambiente propicio para la gobernanza y el ejercicio del buen gobierno, ya que los procesos de auditoria social que pueden ejercerse a traves del seguimiento de las erogaciones publicas durante esta coyuntura contribuiran a fomentar la legitimidad politica y como aporte para el proceso de gestion politica de la salud en el marco de la coyuntura COVID-19. Desde inicios de la Pandemia anteriormente referida, la Alianza Mundial para el Gobierno Abierto, ha infundido en los paises miembros de la iniciativa la necesidad del abordaje de la coyuntura COVID-19 en los Estados miembros de la  Alianza, razon por la cual, esta tematica responde a las necesidades actuales y coyunturales de atencion en los planes de accion nacional de gobierno abierto a nivel nacional e internacional.')),
    ('gestion_publica_e_inclusion_social', _(u'Los entes administrativos se instituyen con la finalidad de garantizar el cumplimiento de los derechos humanos de la poblacion, a traves de la efectiva prestacion de servicios publicos orientados al cumplimiento de los deberes del Estado, consagrados en la normativa juridico- politica y administrativa del pais. La institucionalidad publica para el cumplimiento de sus competencias y obligaciones materializa acciones publicas enmarcadas en politicas, planes y proyectos gubernamentales con la finalidad de propiciar el desarrollo social que implica la garantia del cumplimiento de los derechos humanos de la poblacion, pudiendo ser estos, derechos economicos y sociales, civiles y politicos y culturales, entre otros. El estado de derecho se fundamenta en que las instituciones publicas cumplan con el fin para el cual fueron instituidas en cumplimiento de los fundamentos normativos de caracter administrativo. No se garantiza el cumplimiento de los derechos humanos de la poblacion sin la existencia de una institucionalidad publica fortalecida y que ejerza su funcion hacia la busqueda de un desarrollo social sostenido. La garantia del cumplimiento de los derechos humanos depende de entre otras acciones, del impulso de la accion gubernamental orientada hacia la universalizacion de la prestacion de servicios publicos, lo cual, hace necesario el impulso de acciones publicas orientadas al fomento de la inclusion o al hacer mas inclusiva la prestacion de servicios publicos fortaleciendo la democratizacion de la gestion publica.')),
    ('medio_ambiente_cambio_climatico_y_gestion_integral_para_la_reduccion_del_riesgo_a_desastres', _(u'Dentro de los temas sociales y politicos que se han convertido como parte de la agenda politica internacional en distintos espacios de toma de decisiones a nivel global se encuentra lo concerniente al planteamiento de propuestas orientadas a la generacion de un desarrollo sostenible a nivel mundial a traves del cuidado del medio ambiente y de la inclusion de politicas sostenibles para el abordaje del tema ambiental. Asimismo, la garantia de resguardar la seguridad de la personal como un deber del Estado hace imperante la necesidad de contar con acciones gubernamentales orientadas a reducir el riesgo a desastres en paises vulnerables por su situacion ambiental y geografica, lo cual hace necesario un acercamiento al ambito social por parte del ente que guia la accion politica del Estado, para poder consensuar acciones orientadas a salvaguardar la vida y seguridad de los habitantes.')),
    ('reduccion_de_la_pobreza_y_migracion', _(u'Derivado a factores principalmente de origen economico y sus derivados efectos sociales, los Estados como el guatemalteco afrontan una serie de problemas publicos que deben ser atendidos por parte de los gobiernos en turno, ya que sus efectos producen la migracion de sus habitantes hacia otros territorios en busqueda de mejores condiciones de vida y desarrollo social, que no han sido garantizadas por el Estado. La migracion produce efectos economicos y sociales tambien en otros paises, proyectandose los problemas internos de un Estado en otros territorios a nivel internacional, lo cual, conlleva a afirmar que la migracion es una problematica que afrontan los Estados a nivel mundial y que debe buscarse soluciones en espacios internacionales los cuales han  sido impulsados por parte de organismos internacionales y programas a nivel mundial con la finalidad que los paises incluyan esa sus agendas politicas, en sus planes gubernamentales propuestas para superar los efectos de la migracion y la atencion a este problema internacional.')),
)
